[package]
name = "cli"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = { version = "1.0.83"}
clap = { version = "4.5.4", features = ["derive"] }
forward-to-the-future = { path = "../forward-to-the-future" }

[lints]
workspace = true

[[bin]]
name = "store-cli"
path = "src/main.rs"