[package]
name = "forward-to-the-future"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
assertor = { version = "0.0.2", features = ["testing"] }
itertools = "0.13.0"
regex = "1.10.4"

[lints]
workspace = true
